version: '3'
services:
  db:
    image: postgres:alpine
    container_name: database
    environment:
      POSTGRES_DB: social-media
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
